### PR TITLE
feat(test-runner-v3): add task_id in test results

### PR DESCRIPTION
**Pull request by jelorivera08**
Issue: https://github.com/exercism/typescript-test-runner/issues/16

This PR uses the `./meta/config.json` to map out the task id and names. and returns a task_id in the results object when everything checks out. 

Changes: 
- Fetch the metadata JSON every time a test starts and assign it to the metadata variable of output.
- in the `testInnerFinished` function, check if a taskId is available for a certain test and have it returned in the results object.

Up for discussion:
- Naming conventions for the key used in the config metadata `test_mapping`.
- Should we fetch the metadata every test or in the initialization of the Output Class?
- More performant way of fetching metadata JSON file.

### CODE REVIEW

**Comment by iHiD** [comment]
Exciting! Thanks 💙

**Comment by ErikSchierboom** [comment]
Great. I've asked @SleeplessByte to review.

**Comment by SleeplessByte** [comment]
As written on Slack:

> :wave: with big things like this, it usually helps to discuss it in an issue first.
>
> What I like about the solution:
> - it works!
> - it's a pretty discoverable way to do it. Great :slightly_smiling_face:
>
> What I don't like about the solution:
> - requires manual syncing
> - requires duplication of quite a bit of content

Originally I envisioned us either adding a decorator or a jest extension (so you could do `jest.task(1)` or even just `task(1)`, or a regular "function call" that would set the task id directly (`task(1)`), or actually use the same reporting comment style to report to the output the task ID (`task(1)` but it actually uses `console.log` under the hood).

These would be called from the first line of the test (so inside the actual test function `test('...', () => { /* here */ })`), or just above the test (`task(1); test('...'`).

The worry I have with manual synching is that it's too easy to get wrong.

What do you think?

**Comment by jelorivera08** [comment]
I agree, @SleeplessByte. I'll create a new PR using your recommendation and see how things would work out! Thanks for the help. Closing this one out.

**Pull request closed without merging**
